#!/bin/sh


SMFSPF_DROPINS_DIR=${SMFSPF_DROPINS_DIR:=/etc/smf-spf.d}
SMFSPF_CONF_FILE=${SMFSPF_CONF_FILE:=/etc/smf-spf.conf}


[ ! -d $SMFSPF_DROPINS_DIR ] && exit 0

for f in $SMFSPF_DROPINS_DIR/*; do
    echo -e "\n\n#\n# $f\n#\n" >> $SMFSPF_CONF_FILE
    cat $f                     >> $SMFSPF_CONF_FILE
done
